// Generated by https://quicktype.io

export interface Hero {
    id:               string;
    superhero:        Publisher;
    publisher:        string;
    alter_ego:        string;
    first_appearance: string;
    characters:       string;
}

export enum Publisher {
    DCComics = "DC Comics",
    MarvelComics = "Marvel Comics"
}